### PR TITLE
Suggestion to include github actions workflow

### PR DESCRIPTION
**Pull request by rajesh-s**
Automatically trigger note-link-janitor on every push to GitHub.

Useful in cases where a yarn installation is not available locally

This is the workflow file: https://gist.github.com/rajesh-s/749c99ef9e7c884828a1acda698e477b

### CODE REVIEW

**Comment by andymatuschak** [comment]
Hm. One tricky aspect of this approach is that this means every time you push to your notes repo, the server modifies a bunch of your notes. Wouldn't you have to always remember to pull afterwards, or else end up with constant merge commits / conflicts?

**Comment by rajesh-s** [comment]
Thanks for taking the time to review this approach! 

>  every time you push to your notes repo, the server modifies a bunch of your notes

Yes, this is correct. 

- The good part about the server doing it (as opposed to manually running it locally) on every push is that it creates a commit that you can revert if you don't like the changes that were made. It adds some sense of inherent backup/vc mechanism to the changes that note-link-janitor makes.
- Since note-link-janitor only modifies the Backlinks section of the notes I think this should be fine

>  Wouldn't you have to always remember to pull afterwards, or else end up with constant merge commits / conflicts?

Yes, a pull before push would be necessary (git reminds of this), but merge conflicts may not be a concern here since the changes that the bot makes are all confined to the "Backlinks" section that the user is unlikely to manually update (atleast I have not encountered conflicts in the two weeks I have been using it this way)

**Comment by andymatuschak** [comment]
Got it. Thanks!

**Comment by sander** [comment]
@rajesh-s Curious: what has your experience been using this workflow since January?

FYI, I’ve experimented with something similar recently to make it easy to use with GitHub Wiki, which includes a nice web-based editor and wiki link rendering:

https://twitter.com/s89/status/1343676654988779520

**Comment by rajesh-s** [comment]
@sander It's been working just like I expected and I'm happy with it. I can push from any device without having to setup note link janitor every time. It turned out to be a do it once and forget kind of solution. Note link janitor works best on every push (as mentioned in the gist) than a cron job. 

Reminder to pull before push is the one thing that'll take a few times to get used to.

**Pull request merged**
